server:
  port: ${BPD_ENROLLMENT_PORT:8080}
  tomcat:
    connection-timeout: ${BPD_ENROLLMENT_SERVER_CONNECTION_TIMEOUT:${SERVER_CONNECTION_TIMEOUT:}}
    max-connections: ${BPD_ENROLLMENT_SERVER_MAX_CONNECTION:${SERVER_MAX_CONNECTION:}}
    processor-cache: ${BPD_ENROLLMENT_SERVER_PROCESSOR_CACHE:${SERVER_PROCESSOR_CACHE:}}
    threads.max: ${BPD_ENROLLMENT_SERVER_THREAD_MAX:${SERVER_THREAD_MAX:}}
    threads.min-spare: ${BPD_ENROLLMENT_SERVER_THREAD_MIN:${SERVER_THREAD_MIN:}}

spring:
  application:
    name: "@project.parent.artifactId@"
    version: "@project.version@"
  profiles:
    include:
      # TO enable italian documentations
      - swaggerIT

info:
  build:
    artifact: "@project.parent.artifactId@"
    name: "@project.parent.artifactId@"
    description: "@project.description@"
    version: "@project.version@"

error-manager:
  enabled: true

meda:
  core:
    sessioncontext:
      enabled: false

logging:
  level:
    it.gov.pagopa.bpd.enrollment: ${LOG_LEVEL_BPD_ENROLLMENT:DEBUG}