apiVersion: apps/v1
kind: Deployment
metadata:
  name: bpdmsenrollment
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: bpdmsenrollment
  template:
    metadata:
      labels:
        app: bpdmsenrollment
    spec:
      containers:
        - name: bpdmsenrollment
          image: cstarprodregistry.azurecr.io/bpdmsenrollment
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: postgres-credentials
            - configMapRef:
                name: eventhub-logging
            - configMapRef:
                name: rest-client
            - configMapRef:
                name: bpdmsenrollment
            - configMapRef:
                name: jvm
          resources:
            limits:
              cpu: '1'
              memory: 4Gi
            requests:
              cpu: 10m
              memory: 256Mi
      hostAliases:
        - hostnames:
            - u87cstarprod.servicebus.windows.net
          ip: 10.70.132.4
