apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: bpdmsenrollement
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: bpdmsenrollement
    spec:
      containers:
        - name: bpdmsenrollement
          image: cstarregistry.azurecr.io/bpdmsenrollement
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: eventhub-logging
            - configMapRef:
                name: rest-client
