apiVersion: apps/v1
kind: Deployment
metadata:
  name: bpdmsenrollment
spec:
  replicas: 18
  selector:
    matchLabels:
      app: bpdmsenrollment
  template:
    metadata:
      labels:
        app: bpdmsenrollment
      annotations:
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: '8080'
        prometheus.io/scrape: 'true'
    spec:
      containers:
        - name: bpdmsenrollment
          image: cstarprodregistry.azurecr.io/bpdmsenrollment
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: postgres-credentials
            - configMapRef:
                name: eventhub-logging
            - configMapRef:
                name: rest-client
            - configMapRef:
                name: bpdmsenrollment
            - configMapRef:
                name: jvm
          resources:
            limits:
              cpu: '1'
              memory: 4Gi
            requests:
              cpu: 50m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 20
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 30
      hostAliases:
        - hostnames:
            - u87cstarprod.servicebus.windows.net
          ip: 10.70.132.4
