apiVersion: apps/v1
kind: Deployment
metadata:
  name: bpdmsenrollement
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: bpdmsenrollement
  template:
    metadata:
      labels:
        app: bpdmsenrollement
    spec:
      containers:
        - name: bpdmsenrollement
          image: cstaruatregistry.azurecr.io/bpdmsenrollement
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: postgres-credentials
            - configMapRef:
                name: eventhub-logging
            - configMapRef:
                name: bpdmsenrollement
            - configMapRef:
                name: jvm                
      hostAliases:
        - hostnames:
            - bpd-event-uat.servicebus.windows.net
          ip: 10.70.67.5
