apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: bpdmsenrollement
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: bpdmsenrollement
    spec:
      containers:
        - name: bpdmsenrollement
          image: cstarregistry.azurecr.io/bpdmsenrollement-uat
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: eventhub-logging
            - configMapRef:
                name: rest-client
      hostAliases:
        - hostnames:
            - bpd-hub-dev.servicebus.windows.net
          ip: 10.70.5.10